---
abstract: 'Call HTML::Entities::encode_entities, via a hash, within a string'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: 0
  Test::Pod: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Entities-Interpolate
provides:
  HTML::Entities::Interpolate:
    file: lib/HTML/Entities/Interpolate.pm
    version: 1.04
requires:
  HTML::Entities: 0
  Tie::Function: 0
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: 1.04
