---
abstract: 'Call HTML::Entities::encode_entities, via a hash, within a string'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: '1.001006'
configure_requires:
  Module::Build: '0.421'
dynamic_config: 1
generated_by: 'Module::Build version 0.4211, CPAN::Meta::Converter version 2.142060'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTML-Entities-Interpolate
provides:
  HTML::Entities::Interpolate:
    file: lib/HTML/Entities/Interpolate.pm
    version: '1.06'
requires:
  HTML::Entities: '0'
  Tie::Function: '0'
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: '1.06'
